### ISSUE TITLE
is node-attempt production ready now?

### ISSUE THREAD

**Issue by siddo420** [TomFrost/node-attempt#6]
Looks interesting and useful, but have you or anyone else ever used it in production?

**Comment by TomFrost** [comment]
This has been used in multiple large and small scale applications since its release mid 2012.

**Comment by siddo420** [comment]
Thanks.

Can I replace 'this' to give arguments to the function call? In your examples, yo've only used flakyApiCall(this).

**Comment by TomFrost** [comment]
`this` is the callback function. Attempt was designed when substack's Seq was the gold standard for control flow, so it follows a similar pattern. Wherever you would normally put a callback function, just pass `this` instead. That will cause the actual callback to execute that you've provided to Attempt.

**Comment by siddo420** [comment]
Sorry, I am new to Node and Javascript. 

Does that mean I cannot pass arguments to my function? The following code seems to work fine though.

```
attempt( attempt_options()
  , function( attempts ){ 
      logger.debugc( "Attempting redis.rpush " + (attempts + 1) + " time." );
      redis.rpush( "pkt:" + user_id,  data ); 
    }
  , function( err, result ){
      if( err ){
        return done( err );
      }
      return done( null );
    }
  ); //eof .attempt()  
```

As you can see, I am trying to call Redis functions multiple times on failure.

Any issues with my code?

**Comment by TomFrost** [comment]
Does `redis.rpush` accept an optional callback function as a final argument? If so, just add `this` as a third argument to that function and you're all set.

**Comment by siddo420** [comment]
Ok I get it now .. yes it does accept a callback.

thanks.
